apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
  - image: andreabrame/people-backend
    name: backend
    env:
    - name: spring.datasource.username
      value: root
    - name: spring.datasource.password
      value: root
    - name: spring.datasource.url
      value: jdbc:mysql://people-backend-db:3306/people?serverTimezone=Europe/Paris
    - name: keycloak.auth-server-url
      value: http://localhost:8080/auth
  - name: backend-db
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: MYSQL_DATABASE
      value: people
    volumeMounts:
    - name: data
      mountPath: /var/lib/mysql

  volumes:
  - name: data
    emptyDir: {}


    