---

# WEB SERVER

- hosts: web
  become: true
  vars_files: 
    - vars/main.yml
    - "vars/{{ ansible_facts['os_family'] }}.yml"
  roles:
   - web



# DATABASE SERVER

- hosts: db
  become: true
  vars_files: 
    - vars/main.yml
    - "vars/{{ ansible_facts['os_family'] }}.yml"
  vars:
    root_password: "Test4589$"
  roles: 
    - database