version: "3"
services:
  hello:
    image: hello
    networks:
      - service-net
    environment: 
      services.message.url: http://message:8081
      services.name.url: http://name:8082
    ports: 
      - "8083:8083"
    depends_on: 
      - name
      - message
  message:
    image: message
    networks:
      - service-net
    expose:
      - 8081
  name:
    image: name
    networks:
      - service-net
      - name-net
    expose:
      - 8082
    environment: 
      spring.datasource.url: jdbc:mysql://name-db:3306/name
      spring.datasource.password: root
    depends_on: 
      - name-db
  name-db:
    image: mysql
    volumes: 
      - name-db-vol:/var/lib/mysql
    networks:
      - name-net
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: name
networks:
  name-net:
  service-net:
volumes: 
  name-db-vol: