# ####################################################################
# ################### CONFIGURATION VARIABLES ########################
# ####################################################################
IMAGE_NAME = "bento/ubuntu-20.04"   # Image to use
MEM = 1048                          # Amount of RAM
CPU = 1                             # Number of processors
SLAVE_NBR = 4                      # Number of slaves node
NETWORK_ADAPTER="wlp3s0"            # Bridge network adapter


Vagrant.configure("2") do |config|
    # RAM and CPU config
    config.vm.provider "virtualbox" do |v|
        v.memory = MEM
        v.cpus = CPU
    end

    # Slave node config
    config.ssh.insert_key = false
    config.vm.define "webapp" do |slave|
        # OS and Hostname
        slave.vm.box = IMAGE_NAME
        slave.vm.hostname = "webapp"
        slave.vm.network "public_network", bridge: NETWORK_ADAPTER, ip: "192.168.0.36"
    end
    config.ssh.insert_key = false
    config.vm.define "mydb" do |slave|
        # OS and Hostname
        slave.vm.box = IMAGE_NAME
        slave.vm.hostname = "mydb"
        slave.vm.network "public_network", bridge: NETWORK_ADAPTER, ip: "192.168.0.37"
    end
    config.ssh.insert_key = false
    config.vm.define "mydb-readonly" do |slave|
        # OS and Hostname
        slave.vm.box = IMAGE_NAME
        slave.vm.hostname = "mydb-readonly"
        slave.vm.network "public_network", bridge: NETWORK_ADAPTER, ip: "192.168.0.38"
    end
end
